Implementation of Prefix domain
BlueRyse/lisa pull request #1
Opened 2022-10-27 13:07 UTC by BlueRyse

WIP

2022-10-27 13:10 UTC, VincenzoArceri requested changes

2022-10-27 13:10 UTC, VincenzoArceri commented on lisa/lisa-core/src/main/java/it/unive/lisa/analysis/string/Prefix.java
> +        return false;
We should implement this method.

2022-10-27 13:10 UTC, VincenzoArceri commented on lisa/lisa-core/src/main/java/it/unive/lisa/analysis/string/Prefix.java
> +
We should override `isTop` and `isBottom` methods.

2022-10-27 13:10 UTC, VincenzoArceri commented on lisa/lisa-core/src/main/java/it/unive/lisa/analysis/string/Prefix.java
> +            return this;
In this case we should return `TOP`

2022-10-27 13:10 UTC, VincenzoArceri commented on lisa/lisa-core/src/main/java/it/unive/lisa/analysis/string/Prefix.java
> +        if(operator == StringConcat.INSTANCE){
For all the symbolic expressions for which we cannot return a prefix (e.g., StringContains), we should return `TOP`, not the least upper bound between `left` and `right`

2022-10-27 14:47 UTC, BlueRyse commented
@VincenzoArceri Requested changes implemented
Ready for review

2022-11-15 18:10 UTC, VincenzoArceri approved these changes

2022-11-15 18:10 UTC, VincenzoArceri commented on lisa/lisa-core/src/main/java/it/unive/lisa/analysis/string/Prefix.java
> +            return new Prefix(result.toString());
ToString not needed here

2022-11-15 18:10 UTC, merged